services:
  mdbook:
    build: 
      context: .
      dockerfile_inline: |
        FROM peaceiris/mdbook:v0.5.0-rust
        COPY . /book
        WORKDIR /book
    ports:
      - '3000:3000'
    command: ["serve", "--hostname", "0.0.0.0"]